# Generated by Django 3.2.3 on 2021-06-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='name',
        ),
        migrations.AddField(
            model_name='child',
            name='fname',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='child',
            name='lname',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='parent',
            name='fname',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='parent',
            name='lname',
            field=models.CharField(default='name', max_length=200),
        ),
    ]
