# Generated by Django 3.2.3 on 2021-06-12 22:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210612_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='age',
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
