# Generated by Django 3.2.3 on 2021-06-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20210612_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='child',
        ),
        migrations.AddField(
            model_name='week',
            name='child',
            field=models.ManyToManyField(to='schedule.Child'),
        ),
    ]
